trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Stage1
    displayName: "First Stage"

    jobs:
      - job: Job1
        displayName: "First Job"
        steps:
          - checkout: none

          - script: echo "This is the first job in the first stage."
            displayName: "Run a simple script"

      - job: Job2
        displayName: "Job continueOnError: true"
        dependsOn: Job1
        continueOnError: true
        steps:
          - checkout: none

          - script: exit 1
            displayName: "Fail this job"

          - script: echo "This job will not run because the previous job failed."
            displayName: "This will not run"

          - script: echo "This job will always run."
            displayName: "This will always run"
            condition: always()

      - job: Job3
        displayName: "Third Job"
        dependsOn: Job2
        steps:
          - checkout: none

          - script: echo "This job should run because the previous job is set to continue on error."
            displayName: "Run this job"

          - script: |
              echo "This step will fail, but should not stop subsequent steps"
              exit 1
            displayName: "Step continueOnError: true"
            continueOnError: true

          - script: echo "This step will run even if the previous step failed."
            displayName: "Run this step after a failed step"

      - job: Job5
        displayName: "succeededOrFailed"
        dependsOn: Job2
        condition: succeededOrFailed()
        steps:
          - checkout: none

      - job: Job6
        displayName: "succeeded()"
        dependsOn: Job2
        condition: succeeded()
        steps:
          - checkout: none

      - job: Job7
        displayName: "failed()"
        dependsOn: Job2
        condition: failed()
        steps:
          - checkout: none
          
      - job: Job8
        displayName: "not(failed())"
        dependsOn: Job2
        condition: not(failed())
        steps:
          - checkout: none

  - stage: Stage2
    displayName: "Second Stage"

    jobs:
      - job: Job4
        displayName: "Fourth Job"
        steps:
          - checkout: none

          - script: echo "This is the fourth job in the second stage."
            displayName: "Run a simple script in second stage"